# Generated by Django 4.1.3 on 2022-11-14 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_actor_email_actor_phone_alter_revenue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 11, 14)),
        ),
    ]
