# Generated by Django 4.1.3 on 2022-11-14 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_expense_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.card'),
        ),
    ]
