# Generated by Django 4.1.3 on 2022-11-14 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_expense_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 11, 14)),
        ),
    ]
