# Generated by Django 4.1.3 on 2022-11-15 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_expense_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 11, 15)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 11, 15)),
        ),
    ]
