# Generated by Django 4.1.3 on 2022-11-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_budget_description_alter_expense_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='installment_plan',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
