# Generated by Django 4.1.3 on 2022-11-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_expense_installment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='installment_amount',
            field=models.IntegerField(default=0),
        ),
    ]
