# Generated by Django 4.1.3 on 2022-11-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_budget_value_alter_expense_installment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
