# Generated by Django 4.1.3 on 2022-11-16 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_expense_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='fixed_expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 11, 16)),
        ),
    ]
